INSERT INTO Quiz (categoryName, description)
VALUES
  ('Culture Générale', 'Explorez l'étendue fascinante de la connaissance dans cette catégorie de culture générale. Ce quiz vous offre un voyage à travers divers domaines intellectuels, des arts et de la littérature à la science, en passant par l'histoire et la géographie. Mettez à l'épreuve votre compréhension du monde qui vous entoure en répondant à des questions diversifiées. Des faits surprenants aux concepts fondamentaux, ce quiz est conçu pour défier et élargir vos horizons intellectuels. Plongez dans le défi de la culture générale et découvrez à quel point votre esprit est riche en informations variées !'),
  ('Animaux', 'Entrez dans le royaume fascinant de la faune avec cette catégorie dédiée aux animaux. Que vous soyez un amoureux des animaux ou simplement curieux du règne animal, ce quiz offre un voyage à travers la diversité extraordinaire des créatures qui partagent notre planète. Des animaux domestiques aux espèces sauvages, des fonds marins aux cieux, testez vos connaissances sur les caractéristiques uniques, les habitats, les comportements et les curiosités du monde animal. Préparez-vous à être émerveillé par la beauté et la complexité du règne animal, et mesurez-vous à ce défi captivant sur les merveilles de la nature.'),
  ('Musique', 'Plongez dans l'univers envoûtant de la musique avec cette catégorie dédiée aux mélodies, aux rythmes et aux artistes qui ont façonné le paysage sonore. Que vous soyez un mélomane passionné ou un auditeur occasionnel, ce quiz explore les genres musicaux variés, les légendes de la musique, les instruments emblématiques et les moments clés de l'histoire musicale. Testez vos connaissances sur les paroles, les mélodies et les artistes qui ont laissé une empreinte indélébile dans le monde de la musique. Préparez-vous à un voyage mélodique à travers les décennies et les genres, et découvrez à quel point vous êtes accordé avec l'univers musical !'),
  ('Mythologie et Folklore', 'Explorez les récits mystiques et les légendes envoûtantes de cette catégorie dédiée à la mythologie et au folklore. Plongez dans les mythes anciens, les dieux et déesses, les créatures mythiques et les contes folkloriques qui ont captivé l'imagination humaine à travers les siècles. Ce quiz vous transporte à travers diverses cultures, des mythes grecs aux légendes nordiques, en passant par les histoires asiatiques et bien d'autres encore.'),
  ('Langues', 'Plongez dans la diversité fascinante des langues à travers cette catégorie qui explore le monde riche et complexe de la communication humaine. Que vous soyez passionné par les langues étrangères, les linguistiques ou la linguistique, ce quiz mettra vos compétences linguistiques à l'épreuve. Des langues vivantes aux langues anciennes, des particularités grammaticales aux curiosités lexicales, explorez les nuances et les subtilités qui font de chaque langue une forme unique d'expression. Préparez-vous à un défi où les mots deviennent des énigmes et où la diversité linguistique devient le terrain de jeu. Mesurez-vous à la complexité des langues du monde et découvrez à quel point vous êtes polyglotte !'),
  ('Sport', 'Cette catégorie vous emmène dans l'univers palpitant du sport, où l'adrénaline et la compétition se rencontrent. Des exploits athlétiques mémorables aux moments de victoire exaltants, ce quiz explore le vaste monde du sport sous toutes ses facettes. Que vous soyez un amateur passionné ou un spectateur occasionnel, testez vos connaissances sur les règles, les athlètes légendaires, les records historiques et les événements marquants de différentes disciplines sportives. Préparez-vous à plonger dans l'action captivante et à relever le défi sportif de cette catégorie stimulante !'),
  ('Histoire', 'Voyagez à travers les époques et les civilisations avec cette catégorie dédiée à l'histoire. Que vous soyez passionné par les événements mondiaux, les grandes figures historiques ou les périodes marquantes, ce quiz explore le passé riche et varié de l'humanité. Des batailles épiques aux révolutions culturelles, des découvertes scientifiques aux grandes migrations, testez vos connaissances sur les moments clés qui ont façonné notre monde. Plongez dans les intrigues historiques, mesurez-vous aux faits mémorables et découvrez à quel point vous êtes calé(e) dans l'histoire fascinante de l'humanité. Préparez-vous à un voyage à travers le temps et à un défi captivant qui mettra à l'épreuve votre compréhension du passé.'),
  ('Capitales du Monde', 'Explorez le monde à travers cette catégorie captivante qui met en lumière les capitales des nations. Que vous soyez un globe-trotter aguerri ou un amateur de géographie, ce quiz vous emmène dans un périple mondial à la découverte des centres politiques et culturels de chaque pays. Testez vos connaissances sur les capitales des continents, sur leur histoire et sur les curiosités qui les rendent uniques. De Washington à Tokyo, de Berlin à Canberra, mesurez-vous aux mystères géographiques et découvrez à quel point vous maîtrisez l'essence des capitales du monde. Préparez-vous à un défi cartographique et explorez les coins les plus emblématiques de la planète !'),
  ('Cinéma', 'Entrez dans le monde magique du cinéma avec cette catégorie dédiée au septième art. Que vous soyez un cinéphile chevronné ou un amateur occasionnel, ce quiz explore l'univers passionnant des films, des acteurs emblématiques aux réalisateurs visionnaires. Testez vos connaissances sur les classiques du cinéma, les genres variés, les répliques célèbres et les moments cinématographiques marquants. De l'âge d'or d'Hollywood aux productions contemporaines du monde entier, plongez dans les intrigues captivantes et les mondes cinématographiques uniques. Préparez-vous à un défi où le projecteur est braqué sur votre connaissance du septième art, et découvrez à quel point vous êtes incollable sur le cinéma !');

INSERT INTO Question (qestText, quizID) 
VALUES ("Quelle est la plus grande planète du système solaire ?", 1)
,("Qui a écrit la pièce de théâtre 'Hamlet' ?", 1)
,("Quel est le plus long fleuve du monde ?", 1)
,("En quelle année a eu lieu la Révolution française ?", 1)
,("Quel élément chimique a pour symbole 'Na' ?", 1)
,("Qui a découvert la pénicilline ?", 1)
,("Quel est le plus grand océan de la Terre ?", 1)
,("Qui a peint 'La Joconde' ?", 1)
,("Quel est le deuxième pays le plus peuplé du monde ?", 1)
,("Quelle est la capitale de l'Australie ?", 1)
,("Quelle est la plus haute montagne du monde ?", 1)
,("Qui a écrit '1984' ?", 1)
,("Quel est le plus grand désert du monde ?", 1)
,("Quelle est la monnaie officielle du Japon ?", 1)
,("Quel est le plus grand mammifère terrestre ?", 1)
,("Qui a remporté le prix Nobel de la paix en 2020 ?", 1)
,("Quelle est la période de révolution de la Terre autour du Soleil ?", 1)
,("Quel est le compositeur de la Symphonie n°9 en ré mineur, également appelée la Neuvième Symphonie ?", 1)
,("Quelle est la plus grande île du monde ?", 1)
,("En quelle année a eu lieu la première guerre mondiale ?", 1)
,("Quel est le plus grand lac d'Afrique ?", 1)
,("Qui a écrit 'Le Petit Prince' ?", 1)
,("Quel est le nom de la première femme pilote à avoir traversé l'Atlantique en solitaire ?", 1)
,("Quelle est la deuxième planète du système solaire ?", 1)
,("Qui a découvert la structure en double hélice de l'ADN ?", 1)
,("Quelle est la plus grande barrière de corail au monde ?", 1)
,("Quel est le plus grand État des États-Unis en termes de superficie ?", 1)
,("Qui a écrit 'Crime et Châtiment' ?", 1)
,("Quel est le plus haut sommet d'Afrique ?", 1)
,("En quelle année a eu lieu la première expédition humaine sur la Lune ?", 1)
,("Quel est le plus grand mammifère marin ?", 1)
,("Qui a conçu la théorie de la relativité restreinte ?", 1)
,("Quel est le plus long fleuve d'Europe ?", 1)
,("Qui a écrit 'Orgueil et Préjugés' ?", 1)
,("Quelle est la capitale de l'Afrique du Sud ?", 1)
,("Quel est le plus grand canyon du monde ?", 1)
,("Qui a écrit 'Les Misérables' ?", 1)
,("Quel est le plus grand lac d'Amérique du Nord ?", 1)
,("Qui a peint 'Les Tournesols' ?", 1)
,("Quelle est la capitale de la Norvège ?", 1)
,("Quelle est la planète la plus éloignée du Soleil dans notre système solaire ?", 1)
,("Qui a écrit 'Le Portrait de Dorian Gray' ?", 1)
,("Quel est le plus grand océan du monde en superficie ?", 1)
,("Quelle est la capitale de la Suède ?", 1)
,("Qui a découvert la radioactivité ?", 1)
,("Quel est le plus grand animal terrestre ?", 1)
,("Qui a écrit 'L'Odyssée' ?", 1)
,("Quel est le plus grand lac d'Amérique du Sud ?", 1)
,("Quelle est la première lettre de l'alphabet grec ?", 1)
,("Qui a été le premier homme à marcher sur la Lune ?", 1);

INSERT INTO Question (qestText, quizID) 
VALUES 
("Quel est le plus grand mammifère terrestre ?", 2),
("Quel oiseau détient le record du plus grand envergure d'ailes ?", 2),
("Quelle espèce de serpent est la plus venimeuse au monde ?", 2),
("Quel est le plus grand mammifère marin ?", 2),
("Quel animal est capable de changer de couleur pour se camoufler ?", 2),
("Quelle espèce de tortue est la plus grande du monde ?", 2),
("Quel est le plus grand prédateur terrestre ?", 2),
("Quel animal est surnommé le 'tueur silencieux' en raison de sa chasse furtive ?", 2),
("Quel est l'insecte le plus lourd du monde ?", 2),
("Quel est le plus grand reptile vivant sur terre ?", 2),
("Quel animal est capable de survivre sans eau en absorbant l'humidité de l'air ?", 2),
("Quelle espèce de singe est la plus grande ?", 2),
("Quel oiseau est capable de voler en arrière ?", 2),
("Quel mammifère marin est également connu sous le nom de 'licorne des mers' en raison de sa défense unique ?", 2),
("Quel est le plus grand insecte du monde en termes de taille corporelle ?", 2),
("Quelle espèce de serpent est la plus venimeuse en termes de toxicité de son venin ?", 2),
("Quel animal est connu pour son intelligence exceptionnelle, notamment l'utilisation d'outils ?", 2),
("Quelle est la plus grande espèce de baleine ?", 2),
("Quel est le plus grand félin sauvage ?", 2),
("Quel oiseau est capable de dormir en volant pendant de longues périodes ?", 2),
("Quel reptile est capable de régénérer ses membres perdus ?", 2),
("Quel est le plus grand singe du monde ?", 2),
("Quelle espèce de chauve-souris est la plus grande au monde ?", 2),
("Quel est le plus grand insecte volant du monde ?", 2),
("Quel animal est capable de changer de sexe au cours de sa vie ?", 2),
("Quelle espèce de serpent est la plus venimeuse en termes de rapidité d'injection de son venin ?", 2),
("Quel est le plus grand prédateur marin ?", 2),
("Quel animal est capable de voir les rayons ultraviolets ?", 2),
("Quelle espèce de méduse est considérée comme la plus venimeuse au monde ?", 2),
("Quel est le plus grand insecte du monde en termes de longueur ?", 2),
("Quelle espèce de singe est la plus petite du monde ?", 2),
("Quel est le plus grand oiseau du monde ?", 2),
("Quelle espèce de grenouille est considérée comme la plus venimeuse au monde ?", 2),
("Quel animal est capable de régénérer son cœur et d'autres organes vitaux ?", 2),
("Quelle espèce de tortue est la plus rapide sur terre ?", 2),
("Quel est le plus grand rongeur du monde ?", 2),
("Quelle espèce de poisson est connue pour son électrolocalisation ?", 2),
("Quel animal est capable de planer sur de longues distances en utilisant des membranes entre ses pattes ?", 2),
("Quelle espèce de singe est connue pour son nez proéminent ?", 2),
("Quel animal est capable de voir dans le noir total grâce à sa vision nocturne exceptionnelle ?", 2),
("Quelle est la plus grande espèce de fourmi au monde ?", 2),
("Quel est le plus grand crustacé terrestre ?", 2),
("Quelle espèce de serpent est la plus longue au monde ?", 2),
("Quel est le plus grand animal invertébré marin ?", 2),
("Quelle espèce de poisson est connue pour sa capacité à marcher sur terre ?", 2),
("Quel est le plus grand félin arboricole ?", 2),
("Quelle espèce de phoque est la plus grande ?", 2),
("Quel animal est connu pour ses migrations annuelles massives sur de longues distances ?", 2),
("Quelle est la plus grande espèce de singe au monde ?", 2),
("Quel est le plus grand prédateur terrestre volant ?", 2);

INSERT INTO Question (qestText, quizID) 
VALUES 
("Qui est l'auteur de la Symphonie fantastique ?", 3),
("Quel compositeur autrichien a composé 'Le Requiem' ?", 3),
("Quel instrument est associé à Antonio Vivaldi et son œuvre 'Les Quatre Saisons' ?", 3),
("Qui est le compositeur du célèbre ballet 'Le Lac des cygnes' ?", 3),
("Quelle symphonie de Beethoven est également connue sous le nom de 'Symphonie pastorale' ?", 3),
("Qui a composé l'opéra 'Carmen' ?", 3),
("Quel compositeur russe est connu pour ses ballets 'La Belle au bois dormant' et 'Casse-Noisette' ?", 3),
("Quelle chanson emblématique de Queen commence par les mots 'Is this the real life, is this just fantasy?' ?", 3),
("Quel compositeur romantique allemand est célèbre pour ses 'Lieder' (chants) et ses symphonies, dont la Symphonie n°4 en ré mineur ?", 3),
("Qui a écrit la comédie musicale 'Les Misérables' ?", 3),
("Quel compositeur italien a créé l'opéra 'La Traviata' ?", 3),
("Quel est le nom du groupe de rock britannique connu pour les albums 'The Dark Side of the Moon' et 'The Wall' ?", 3),
("Qui est le compositeur de la musique du film 'Les Dents de la mer' ?", 3),
("Quelle chanson d'Elton John a remporté l'Oscar de la meilleure chanson originale en 1995 ?", 3),
("Quel musicien et compositeur américain est souvent surnommé 'The King of Pop' ?", 3),
("Qui a composé la 'Marche impériale', également connue comme le thème de Dark Vador dans Star Wars ?", 3),
("Quel est le nom du groupe de rock nord-irlandais connu pour les chansons 'With or Without You' et 'Sunday Bloody Sunday' ?", 3),
("Quelle chanteuse américaine est surnommée 'Queen of Pop' ?", 3),
("Qui a composé l'opéra 'La Flûte enchantée' ?", 3),
("Quel est le nom du groupe suédois de pop qui a remporté l'Eurovision en 1974 avec la chanson 'Waterloo' ?", 3),
("Quel compositeur autrichien a créé la 'Messe en si mineur' ?", 3),
("Qui a composé 'La Moldau', poème symphonique dépeignant le cours du fleuve Vltava en Bohême ?", 3),
("Quelle chanteuse britannique est connue pour les tubes 'Rolling in the Deep' et 'Someone Like You' ?", 3),
("Quel musicien et compositeur allemand a créé les 'Quatre Saisons' de Vivaldi ?", 3),
("Qui a composé l'opéra 'Tosca' ?", 3),
("Quel groupe de rock britannique est connu pour les albums 'The Joshua Tree' et 'Achtung Baby' ?", 3),
("Qui a composé la musique du ballet 'Roméo et Juliette' ?", 3),
("Quelle chanteuse américaine est surnommée 'The Queen of Soul' ?", 3),
("Qui a écrit l'opéra 'Madame Butterfly' ?", 3),
("Quelle chanson du groupe Queen est souvent associée au film 'Wayne's World' ?", 3),
("Quel compositeur autrichien est célèbre pour ses symphonies, dont la 'Symphonie n°41' (Jupiter) ?", 3),
("Qui a composé la 'Sonate au clair de lune' ?", 3),
("Quel groupe britannique a sorti l'album 'Abbey Road' en 1969 ?", 3),
("Qui est le compositeur de la musique du film 'Le Seigneur des Anneaux' ?", 3),
("Quelle chanteuse américaine est connue pour les chansons 'Poker Face' et 'Bad Romance' ?", 3),
("Qui a composé 'La Chevauchée des Walkyries' ?", 3),
("Quel instrument est associé au compositeur Johann Sebastian Bach ?", 3),
("Quelle chanteuse britannique a interprété la chanson 'Skyfall' pour le film du même nom de James Bond ?", 3),
("Qui a composé la 'Marche hongroise' ?", 3),
("Quel compositeur russe est célèbre pour son ballet 'Le Lac des cygnes' ?", 3),
("Quel groupe de rock britannique est connu pour les albums 'Sticky Fingers' et 'Exile on Main St.' ?", 3),
("Qui a composé la musique du film 'Jurassic Park' ?", 3),
("Quel instrument est associé au compositeur russe Sergei Rachmaninoff ?", 3),
("Qui a écrit la chanson 'Imagine' ?", 3),
("Quel compositeur autrichien a créé l'opéra 'Don Giovanni' ?", 3),
("Quel artiste américain est connu pour les chansons 'Purple Haze' et 'Hey Joe' ?", 3),
("Qui a composé l'opéra 'La Bohème' ?", 3),
("Quelle chanteuse américaine est surnommée 'The Material Girl' ?", 3),
("Qui est le compositeur de la musique du film 'E.T. l'extra-terrestre' ?", 3),
("Quel groupe de rock américain est connu pour l'album 'The Wall' ?", 3);

